// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2s1mECnS0f5_b7c-LoUWh0LKOx6GlOro',
    appId: '1:715919077172:web:2560502e2c738d63e13f61',
    messagingSenderId: '715919077172',
    projectId: 'curdproject-95cc1',
    authDomain: 'curdproject-95cc1.firebaseapp.com',
    storageBucket: 'curdproject-95cc1.firebasestorage.app',
    measurementId: 'G-3MJ13TEK2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBimzg6UnE3Hc-K_Jn3F7tudyHULO4rlqU',
    appId: '1:715919077172:android:2aa350b1ef6552bbe13f61',
    messagingSenderId: '715919077172',
    projectId: 'curdproject-95cc1',
    storageBucket: 'curdproject-95cc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCvO5cVc-G9Q4H0nw_vSTVY8QyLoPebrA',
    appId: '1:715919077172:ios:be4835b0fc1ae86ae13f61',
    messagingSenderId: '715919077172',
    projectId: 'curdproject-95cc1',
    storageBucket: 'curdproject-95cc1.firebasestorage.app',
    iosBundleId: 'com.example.curdFirebase',
  );
}
